python run_qc.py
python run_qc_plots.py
python run_integration.py
python run_integration_plots.py
python run_clus.py
python run_clus_plots.py
python run_annot.py
python run_annot_plots.py
python run_coda.py
python run_coda_plots.py